name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    name: Test
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        node-version: [ 10.x, 12.x, 14.x, 15.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #      - name: Use Node.js ${{ matrix.node-version }}
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: src/**/*.spec.js