name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [15, 16, 18]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          component: true
          tag: node-${{ matrix.node }}